---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 怪脾气.
--- DateTime: 2023/8/28 15:05
---
-- 优惠券id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]

-- 库存的kye
local stockKye = 'seckill:stock:' .. voucherId
-- 订单的key
local orderKye = 'seckill:order:' .. voucherId
-- 判断库存是否充足
if (tonumber(redis.call('get', stockKye)) <= 0) then
    -- 坤村不足
    return 1
end
-- 用户一人一单
if (redis.call('sismember', orderKye, userId) == 1) then
    return 2
end

--扣减库存
redis.call('incrby',stockKye,-1)
-- 下单
redis.call('sadd',orderKye,userId)
return 0